channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.9
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - pyspark
  - scikit-learn
  - wandb
  - ipykernel
  - matplotlib
  - seaborn
